apiVersion: v1
kind: Template
metadata:
  name: chat-app
labels:
  app: chat-app
parameters:
  - name: INFRA_PROJECT
    description: Project used for build infrastructure.
    displayName: Infrastructure Project
    value: ui-components-build
    required: true
  - name: PROJECT
    description: Project to set up.
    displayName: Project
    required: true
  - name: APP_NAME
    description: Name of the application.
    displayName: Application Name
    value: chat-app
    required: true
  - name: DEPLOY_TAG
    description: Tag of the ImageStream to deploy.
    displayName: Deploy Tag
    value: latest
    required: true
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        apply-init: true
      name: ${APP_NAME}
      namespace: ${INFRA_PROJECT}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        apply-init: true
      name: ${APP_NAME}
      namespace: ${INFRA_PROJECT}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: '${APP_NAME}:latest'
      runPolicy: Serial
      source:
        binary: {}
        type: Binary
      strategy:
        dockerStrategy:
          buildArgs:
            - name: PROJECT
              value: chat-app
          dockerfilePath: .openshift/chat-app/Dockerfile
        type: Docker
      triggers: []
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        apply-init: true
      name: ${APP_NAME}
      namespace: ${PROJECT}
    data:
      configuration: |-
        {
          "access": {
            "url": "https://access.alberta.ca",
            "realm": "",
            "client_id": ""
          },
          "directory": {
            "url": "https://tenant-service.adsp.alberta.ca"
          }
        }
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT}
    spec:
      replicas: 2
      selector:
        name: ${APP_NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            name: ${APP_NAME}
        spec:
          containers:
            - name: ${APP_NAME}
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 3333
                  name: http
                  protocol: TCP
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /opt/app-root/src/config
                  name: config-volume
              resources:
                limits:
                  cpu: 200m
                  memory: 200Mi
                requests:
                  cpu: 20m
                  memory: 50Mi
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          volumes:
            - configMap:
                defaultMode: 420
                items:
                  - key: configuration
                    path: config.json
                name: ${APP_NAME}
              name: config-volume
      triggers:
        - imageChangeParams:
            containerNames:
              - ${APP_NAME}
            from:
              kind: ImageStreamTag
              name: '${APP_NAME}:${DEPLOY_TAG}'
              namespace: ${INFRA_PROJECT}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT}
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        name: ${APP_NAME}
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT}
    spec:
      port:
        targetPort: http
      tls:
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}
        weight: 100
      wildcardPolicy: None
