/chat/v1/rooms:
  get:
    tags: 
      - Chat
    description: Gets available rooms.
    responses:
      200:
        description: Request completed successfully.
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id: 
                    type: string
                  name:
                    type: string
                  description:
                    type: string
/chat/v1/rooms/{roomId}:
  get:
    tags: 
      - Chat
    description: Get information about a room.
    parameters:
      - name: roomId
        description: ID of the room to get information for.
        in: path
        required: true
        schema:
          type: string
    responses:
      200:
        description: Request completed successfully.
        content:
          application/json:
            schema:
              type: object
              properties:
                id: 
                  type: string
                name:
                  type: string
                description:
                  type: string

/chat/v1/rooms/{roomId}/messages:
  get:
    tags: 
      - Chat
    description: Gets messages in a room.
    parameters:
      - name: roomId
        description: ID of the room to get messages for.
        in: path
        required: true
        schema:
          type: string
    responses:
      200:
        description: Request completed successfully.
        content:
          application/json:
            schema:
              type: object
              properties:
                results:
                  type: array
                  items:
                    type: object
                    properties:
                      hash: 
                        type: string
                      timestamp:
                        type: string
                        format: date-time
                      message:
                        oneOf:
                          - type: string
                          - type: array
                      room: 
                        type: string
                      from:
                        type: object
                        properties:
                          id: 
                            type: string
                          name:
                            type: string
                page:
                  type: object
                  properties:
                    after:
                      type: string
                    next:
                      type: string
                    size:
                      type: number