export const environment = {
  production: false,
  port: '3335',
  TENANT_REALM: null,
  ACCESS_SERVICE_URL: null,
  DIRECTORY_SERVICE_URL: null,
  CLIENT_ID: 'urn:ads:autotest:acronym-service',
  CLIENT_SECRET: null,
  REDIS_HOST: 'acronym-redis',
  REDIS_PORT: 6379,
  REDIS_PASSWORD: null,
  BOT_APP_TYPE: 'SingleTenant',
  BOT_TENANT_ID: null,
  BOT_CLIENT_ID: null,
  BOT_CLIENT_SECRET: null,
  TRUSTED_PROXY: 'uniquelocal',
  LOG_LEVEL: 'debug',
  ...process.env,
};
